function [fitresult, gof] = createFit(distance, voltage_SS)
%CREATEFIT(DISTANCE,voltage_SS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: distance
%      Y Output: voltage_SS
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Oct-2024 19:12:38


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( distance, voltage_SS );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Line of Best Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Voltage of South with Sheild vs Distance', 'Line of Best Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Distance (mm.)', 'Interpreter', 'none' );
ylabel( 'Voltage (V)', 'Interpreter', 'none' );
title('South with Sheild');
grid on


